image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  - npm ci # установка зависимостей из package-lock.json

build: off # отключение встроенной в appveyor системы сборки

build_script:
  - npm run build # сборка проекта

test_script:
  - npm run lint # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
